### ISSUE TITLE
Allowed to be called programmatically as a library

### ISSUE THREAD

**Issue by Zxilly** [cloudwego/goref#16]
**Is your feature request related to a problem? Please describe.**

I'm writing the project https://github.com/Zxilly/go-size-analyzer, a program that can be very memory hungry, so I've added some profilers to monitor performance overhead. The code is at https://github.com/Zxilly/go-size-analyzer/blob/a842f6d50ce2c459435e1961262dc4b97240cef7/cmd/gsa/profiler_main.go#L51-L91

I was hoping there would be a similar way I could replace `pprof.WriteHeapProfile` for the implementation in this repository to achieve a similar effect.

**Describe the solution you'd like**

The call might be able to stop the current process, fork a process to create a snapshot, and then resume.

**Comment by jayantxie** [comment]
I had previously considered integrating it as a pprof http path, but this relies on process forking and intercepting init functions. If there are resource conflicts when the process is running, it can lead to uncontrollable exceptions, so I did not include this feature.
Currently, there is no better solution temporarily. Perhaps after installing the command, you can trigger this command using go exec to capture process memory.
https://github.com/cloudwego/goref/commit/481b9209b1121c6594f7d0a4374758daebd0b592
