### ISSUE TITLE
panic run in the linux

### ISSUE THREAD

**Issue by xmualex2023** [cloudwego/goref#20]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/baedabd2-ad7c-440b-9b02-dbf9b6c226d2)

**Goref version:** 
lastest

Please provide the version of goref you are using.

**Environment:**
linux

The output of `go env`.

**Additional context**

2024-08-19T19:43:31+08:00 error layer=debugger gnu_debuglink CRC check failed for /lib/x86_64-linux-gnu/libresolv-2.31.so (want f549df9f got 7686e521)
2024-08-19T19:43:31+08:00 error layer=debugger gnu_debuglink CRC check failed for /lib/x86_64-linux-gnu/libc-2.31.so (want 9373696 got cd1655d1)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8e89fd]

goroutine 1 [running]:
github.com/cloudwego/goref/pkg/proc.(*mapIterator).kv(0xc0244ca960, 0xc00ad8bb30)
	/Users/alex/Documents/Development/OpenSource/goref/pkg/proc/variables.go:372 +0xdd
github.com/cloudwego/goref/pkg/proc.(*mapIterator).key(...)
	/Users/alex/Documents/Development/OpenSource/goref/pkg/proc/variables.go:361
github.com/cloudwego/goref/pkg/proc.(*ObjRefScope).findRef(0xc0184afa68, 0xc00ad8b270, 0x0)
	/Users/alex/Documents/Development/OpenSource/goref/pkg/proc/reference.go:229 +0x1445
github.com/cloudwego/goref/pkg/proc.ObjectReference(0xc0003380f0, {0x9e5e97, 0x7})
	/Users/alex/Documents/Development/OpenSource/goref/pkg/proc/reference.go:481 +0xc35
github.com/cloudwego/goref/cmd/grf/cmds.execute(0x6f11, {0x0, 0x0}, {0x0, 0x0}, {0x9e5e97, 0x7}, 0xc00024a500)
	/Users/alex/Documents/Development/OpenSource/goref/cmd/grf/cmds/commands.go:139 +0x2b4
github.com/cloudwego/goref/cmd/grf/cmds.attachCmd(0xc00027e100?, {0xc000034c90?, 0x1?, 0x9e29d7?})
	/Users/alex/Documents/Development/OpenSource/goref/cmd/grf/cmds/commands.go:108 +0xf9
github.com/spf13/cobra.(*Command).execute(0xc000212c08, {0xc000034c40, 0x1, 0x1})
	/Users/alex/.gvm/pkgsets/go1.22.2/global/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0xc000212908)
	/Users/alex/.gvm/pkgsets/go1.22.2/global/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0xc0000061c0?)
	/Users/alex/.gvm/pkgsets/go1.22.2/global/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041 +0x13
main.main()
	/Users/alex/Documents/Development/OpenSource/goref/cmd/grf/main.go:22 +0x1a

**Comment by xmualex2023** [comment]
linux does't install go or dlv

**Comment by jayantxie** [comment]
Coincidentally! I also encountered this problem 10 minutes ago.

**Comment by xmualex2023** [comment]
so how to address the problem? install dlv in linux or something?

**Comment by xmualex2023** [comment]
debug-info-directories: ["/usr/lib/debug/.build-id"], the debug info directories is default config? what if it does't exist?

**Comment by jayantxie** [comment]
You can try this pr: https://github.com/cloudwego/goref/pull/21/files
