### ISSUE TITLE
运行时报错 could not resolve parametric type of c:……

### ISSUE THREAD

**Issue by Nyx2022** [cloudwego/goref#23]
**Describe the bug**

运行 grf attach ${PID} 后， 报错

**To Reproduce**

运行 grf attach ${PID}

**Expected behavior**

像 readme的一样正常

**Screenshots**

![image](https://github.com/user-attachments/assets/55dbace1-8e98-4d1b-a0b9-7301a5559a09)

**Goref version:**

goref@v0.0.0-20240819122531-30867097b1fd

**Environment:**

set GO111MODULE=on
set GOARCH=amd64
set GOBIN=
set GOCACHE=
set GOENV=
set GOEXE=.exe
set GOEXPERIMENT=
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GOINSECURE=
go: stripping unprintable or unescapable characters from %"GOMODCACHE"%
set GOMODCACHE=
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
go: stripping unprintable or unescapable characters from %"GOPATH"%
set GOPATH=
set GOPRIVATE=
set GOPROXY=https://goproxy.io,direct
go: stripping unprintable or unescapable characters from %"GOROOT"%
set GOROOT=
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLCHAIN=auto
go: stripping unprintable or unescapable characters from %"GOTOOLDIR"%
set GOTOOLDIR=
set GOVCS=
set GOVERSION=go1.22.6
set GCCGO=gccgo
set GOAMD64=v1
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=0
go: stripping unprintable or unescapable characters from %"GOMOD"%
set GOMOD=
set GOWORK=
set CGO_CFLAGS=-O2 -g
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-O2 -g
set CGO_FFLAGS=-O2 -g
set CGO_LDFLAGS=-O2 -g
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -fno-caret-diagnostics -Qunused-arguments -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map= -gno-record-gcc-switches     

**Additional context**

我的项目中有使用cgo

**Comment by jayantxie** [comment]
这个日志需要优化一下，实际上这个不影响工具正常输出，只是这个日志确实会造成困扰，暂时忽略吧，我优化一下

**Comment by jayantxie** [comment]
fixed: https://github.com/cloudwego/goref/pull/26
