### ISSUE TITLE
grf  panic  when grf is used on apiserver 1.30

### ISSUE THREAD

**Issue by yulongfang** [cloudwego/goref#28]
**Describe the bug**

grf  panic  when grf is used on apiserver 1.30

`[root@iZ8vb98jk2h56dxwo9yjzxZ ~]# /root/gobin/grf  attach 749345 
2024-09-18T16:24:10+08:00 error layer=debugger could not resolve parametric type of s: parametric type without a dictionary
2024-09-18T16:24:10+08:00 error layer=debugger could not resolve parametric type of s: parametric type without a dictionary
2024-09-18T16:24:11+08:00 error layer=debugger read gc data addr error: input/output error
panic: runtime error: makeslice: len out of range

goroutine 1 [running]:
github.com/cloudwego/goref/pkg/proc.cacheMemory({0xa6e1f8?, 0xc000202000}, 0xd8d48c88948046f, 0x20092322d21e8)
        /root/go/pkg/mod/github.com/cloudwego/goref@v0.0.0-20240914064716-e607ae4b8a13/pkg/proc/mem.go:79 +0x126
github.com/cloudwego/goref/pkg/proc.(*HeapScope).readType(0xc0198cf300, 0xc0064ed8c0, 0x6a9732, 0xc003879c88, 0xc00387a000)
        /root/go/pkg/mod/github.com/cloudwego/goref@v0.0.0-20240914064716-e607ae4b8a13/pkg/proc/heap.go:339 +0x1a5
github.com/cloudwego/goref/pkg/proc.(*HeapScope).copyGCMask(0xc0198cf300, 0xc0064ed8c0, 0xc003879c80)
        /root/go/pkg/mod/github.com/cloudwego/goref@v0.0.0-20240914064716-e607ae4b8a13/pkg/proc/heap.go:311 +0xa5
github.com/cloudwego/goref/pkg/proc.(*ObjRefScope).findObject(0xc000537820, 0xc003879ed0, {0xa71dd8, 0xc013fda980}, {0xa6df78?, 0xc022b7ee00?})
        /root/go/pkg/mod/github.com/cloudwego/goref@v0.0.0-20240914064716-e607ae4b8a13/pkg/proc/reference.go:71 +0x113
github.com/cloudwego/goref/pkg/proc.(*ObjRefScope).findRef(0xc000537820, 0xc022c876d0, 0x0)
        /root/go/pkg/mod/github.com/cloudwego/goref@v0.0.0-20240914064716-e607ae4b8a13/pkg/proc/reference.go:177 +0x1bb8
github.com/cloudwego/goref/pkg/proc.ObjectReference(0xc0001ec0f0, {0x9b2efc, 0x7})
        /root/go/pkg/mod/github.com/cloudwego/goref@v0.0.0-20240914064716-e607ae4b8a13/pkg/proc/reference.go:522 +0xc89
github.com/cloudwego/goref/cmd/grf/cmds.execute(0xb6f21, {0x0, 0x0}, {0x0, 0x0}, {0x9b2efc, 0x7}, 0xc000192500)
        /root/go/pkg/mod/github.com/cloudwego/goref@v0.0.0-20240914064716-e607ae4b8a13/cmd/grf/cmds/commands.go:155 +0x2b4
github.com/cloudwego/goref/cmd/grf/cmds.attachCmd(0xc0001ca100?, {0xc000038be0?, 0x1?, 0x9afa57?})
        /root/go/pkg/mod/github.com/cloudwego/goref@v0.0.0-20240914064716-e607ae4b8a13/cmd/grf/cmds/commands.go:124 +0xf9
github.com/spf13/cobra.(*Command).execute(0xc000004600, {0xc000038b90, 0x1, 0x1})
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:989 +0xaa3
github.com/spf13/cobra.(*Command).ExecuteC(0xc000004300)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(0xc0000061a0?)
        /root/go/pkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041 +0x13
main.main()
        /root/go/pkg/mod/github.com/cloudwego/goref@v0.0.0-20240914064716-e607ae4b8a13/cmd/grf/main.go:22 +0x1a`

**To Reproduce**

1.  Create a kubernetes cluster for version 1.30
2. On the node where apiserver resides, use grf attach pid where apiserver resides
3. grf  panic

**Expected behavior**

grf successed

**Screenshots**

**Goref version:**

Please provide the version of goref you are using.

**Environment:**

`GO111MODULE=''
GOARCH='amd64'
GOBIN='/root/gobin'
GOCACHE='/root/.cache/go-build'
GOENV='/root/.config/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='linux'
GOINSECURE=''
GOMODCACHE='/root/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='linux'
GOPATH='/root/go'
GOPRIVATE=''
GOPROXY='https://mirrors.aliyun.com/goproxy/'
GOROOT='/usr/lib/golang'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='local'
GOTOOLDIR='/usr/lib/golang/pkg/tool/linux_amd64'
GOVCS=''
GOVERSION='go1.21.9 (Red Hat 1.21.9-1.0.1.al8)'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='gcc'
CXX='g++'
CGO_ENABLED='1'
GOMOD='/dev/null'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -ffile-prefix-map=/tmp/go-build1461368199=/tmp/go-build -gno-record-gcc-switches'`

**Additional context**

**Comment by jayantxie** [comment]
Try to use `go install github.com/cloudwego/goref/cmd/grf@7c52eea4`, which I added a memory limit to avoid the issue.

**Comment by yulongfang** [comment]
[root@iZ8vb98jk2h56dxwo9yjzxZ gobin]# go install github.com/cloudwego/goref/cmd/grf@7c52eea4
# github.com/cloudwego/goref/pkg/proc
../go/pkg/mod/github.com/cloudwego/goref@v0.0.0-20240914064943-7c52eea490fa/pkg/proc/pcfunc.go:326:6: off declared and not used


can not install Is it a question of my use

**Comment by jayantxie** [comment]
Sorry my fault, `go install github.com/cloudwego/goref/cmd/grf@d57c8d3f`

**Comment by yulongfang** [comment]
Thanks for your help, I used this version to run successfully in my environment

**Comment by jayantxie** [comment]
I'll merge the fixed branch later.
