### ISSUE TITLE
support stackmap/gcdatamask/gcbssmask

### ISSUE THREAD

**Issue by jayantxie** [cloudwego/goref#6]
Currently, the gcmask scanning only supports heap gcmask and does not support stackmap, gcbssmask/gcdatamask. This may lead to some memory being missed in extreme cases. 
FYI: 
https://github.com/golang/go/blob/master/src/runtime/heapdump.go#L270
https://github.com/golang/go/blob/master/src/runtime/heapdump.go#L445

**Comment by jensenojs** [comment]
Is this issue urgent? (I'm a bit worried that I won't be able to finish it in time after taking it over.)

and I haven't read the source code of Golang. What relevant documents or core concepts are helpful for understanding this project?

**Comment by jayantxie** [comment]
It's OK, I guess you're Chinese? Maybe you could refer this book: https://draveness.me/golang/docs/part3-runtime/ch07-memory/golang-memory-allocator/
And I've wrote a article to explain the principle, which can be found in README doc.

**Comment by Zxilly** [comment]
I think it's important, with github.com/Zxilly/go-size-analyzer goref can only recognize a small subset of the memory used. Specifically, only about 300m of the 2000m memory footprint can be recognized.

**Comment by jayantxie** [comment]
> I think it's important, with github.com/Zxilly/go-size-analyzer goref can only recognize a small subset of the memory used. Specifically, only about 300m of the 2000m memory footprint can be recognized.

@Zxilly Unknown types of memory can be identified through gc root mask, but the type information cannot be displayed. Can you provide corresponding core files and executable files? I will analyze the cause of this case and fix it

**Comment by Zxilly** [comment]
I was using attach to collect the info, so no core file can be provided.

**Comment by jayantxie** [comment]
Is there any way for me to reproduce your scene? BTW, you can also manually obtain the core file using the `gcore ${PID}` command

**Comment by Zxilly** [comment]
I didn't know gcore before, I'll return later with the coredump.

**Comment by Zxilly** [comment]
The coredump file is huge, I extreme compressed this file, but it still exceeded the limit allowed by GitHub.
The link is valid for 7 days.

https://www.transfernow.net/dl/20240819pxX6giXG

**Comment by jayantxie** [comment]
Thank you so much! I'll figure out the problem.

**Comment by jayantxie** [comment]
The go version of the given core file is 1.23, which is not supported by goref yet. I am already planning to support it.

**Comment by jayantxie** [comment]
@Zxilly  Have you seen the heap profile? I have confirmed that the total heap span for your core file is 700MB. The 360mb collected by goref is within the normal range. You can use the command `free -h` to check if cache is occupying other memory.

**Comment by jayantxie** [comment]
@Zxilly I have supported the gcrootmask and rescanned the core file you sent. The scanned memory result is the same with the previous. And I have verified that the total memory of all spans in the heap is 676mb, so this should be the actual memory.
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/2073e788-5c31-4b41-9283-2067030c87bc">
Without dwarf:
<img width="1913" alt="image" src="https://github.com/user-attachments/assets/63eb93be-b7ad-4e70-85db-774c40e52bf3">

**Comment by jayantxie** [comment]
@jensenojs What you are referring to is this issue, which has already been resolved. The problem pertains to variables that cannot be scanned by DWARF due to compiler optimizations. A fallback method has been implemented to scan these variables by retrieving them through the stack variable's gcmask and marking them on the optimized function. Here is a simple example:
```go
func malloc() {
	a := make([][]byte, 1024)
	for i := 0;i<=len(a); i++ {
		a[i] = make([]byte, 1024)
	}
	time.Sleep(1 * time.Minute)
}

func main() {
	malloc()
}
```
In the above `malloc` function, which gets inlined, the corresponding variable a cannot be scanned by DWARF. This could potentially overlook the memory it occupies. By falling back to gcmask scanning, we can ensure that the memory referenced by the `malloc` function is accurately counted.
